name: farming_assistant
description: Smart farming app with IoT + AI disease detection (Flutter + Firebase)
publish_to: 'none'
version: 1.0.0+1


environment:
sdk: '>=3.3.0 <4.0.0'


dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.6


# State & utils
provider: ^6.1.2
intl: ^0.19.0
http: ^1.2.2


# Firebase
firebase_core: ^3.4.0
firebase_auth: ^5.1.4
cloud_firestore: ^5.4.4
firebase_database: ^11.0.4
firebase_storage: ^12.3.2
firebase_messaging: ^15.1.3


# Media
image_picker: ^1.1.2
path_provider: ^2.1.4


# On-device ML
tflite_flutter: ^0.11.0
tflite_flutter_helper: ^0.4.4


# Permissions
permission_handler: ^11.3.1


# Charts (optional for sensor graphs)
fl_chart: ^0.68.0


dev_dependencies:
flutter_test:
sdk: flutter
flutter_lints: ^4.0.0


flutter:
uses-material-design: true
assets:
- assets/models/model.tflite
- assets/models/labels.txt
